"use client"

import { motion } from "framer-motion"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { CheckCircle, Award, Users } from "lucide-react"

export default function OwnerSection() {
  const whatsappLink =
    "https://wa.me/447907859528?text=Hi%20Nazakat%20Ali%2C%20I%27m%20interested%20in%20your%20YouTube%20Automation%20course!"

  const credentials = [
    {
      icon: Users,
      title: "1000+ Students",
      description: "Successfully mentored and trained",
    },
    {
      icon: Award,
      title: "5+ Years",
      description: "YouTube automation expertise",
    },
    {
      icon: CheckCircle,
      title: "$500K+",
      description: "Generated by students combined",
    },
  ]

  return (
    <section className="relative py-20 px-4 sm:px-6 lg:px-8 bg-card/20">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"
        >
          {/* Left side - Content */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="space-y-8"
          >
            <div>
              <motion.h2
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                viewport={{ once: true }}
                className="text-5xl sm:text-6xl font-bold mb-4"
              >
                Meet Your Instructor
              </motion.h2>
              <motion.p
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.1 }}
                viewport={{ once: true }}
                className="text-2xl text-accent font-semibold"
              >
                Ale
              </motion.p>
              <motion.p
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.2 }}
                viewport={{ once: true }}
                className="text-lg text-muted-foreground mt-3"
              >
                YouTube Automation Empire Builder & Digital Marketing Expert
              </motion.p>
            </div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              viewport={{ once: true }}
              className="space-y-4"
            >
              <p className="text-lg text-muted-foreground leading-relaxed">
                With over 5 years of expertise in YouTube automation and digital marketing, I've built multiple
                six-figure income streams while maintaining complete anonymity. My mission is to help creators like you
                break free from the traditional 9-5 and build sustainable, automated income.
              </p>
              <p className="text-lg text-muted-foreground leading-relaxed">
                I've personally mentored over 1,000 students, collectively generating over $500,000 in revenue through
                automated YouTube channels. Every strategy taught in this course has been tested and proven to work in
                the real world.
              </p>
            </motion.div>

            {/* Credentials */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.3 }}
              viewport={{ once: true }}
              className="grid grid-cols-3 gap-4"
            >
              {credentials.map((cred, index) => {
                const Icon = cred.icon
                return (
                  <motion.div
                    key={cred.title}
                    initial={{ opacity: 0, scale: 0.8 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.6, delay: index * 0.1 }}
                    viewport={{ once: true }}
                    whileHover={{ translateY: -4 }}
                  >
                    <Card className="glass p-4 text-center hover:glow-gold transition-all h-full">
                      <Icon className="w-8 h-8 text-accent mx-auto mb-2" />
                      <h4 className="font-bold text-sm">{cred.title}</h4>
                      <p className="text-xs text-muted-foreground mt-1">{cred.description}</p>
                    </Card>
                  </motion.div>
                )
              })}
            </motion.div>

            {/* CTA */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              viewport={{ once: true }}
            >
              <a href={whatsappLink} target="_blank" rel="noopener noreferrer">
                <Button
                  size="lg"
                  className="bg-primary hover:bg-primary/90 text-primary-foreground font-bold text-lg h-14 px-10"
                >
                  Chat with Ale
                </Button>
              </a>
            </motion.div>
          </motion.div>

          {/* Right side - Profile Image */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="relative"
          >
            <div className="absolute inset-0 bg-gradient-to-br from-primary/20 to-accent/20 rounded-3xl blur-2xl" />
            <Card className="glass p-8 rounded-3xl overflow-hidden relative z-10 h-full flex items-center justify-center min-h-[500px]">
              <div className="text-center space-y-6">
                <motion.div
                  animate={{ scale: [1, 1.05, 1] }}
                  transition={{ duration: 3, repeat: Number.POSITIVE_INFINITY }}
                  className="text-9xl"
                >
                  <img src="/image/man.jpg" alt="Ale" className="w-full h-full object-cover rounded-3xl" />
                </motion.div>
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Ale</h3>
                  <p className="text-muted-foreground">YouTube Automation Expert</p>
                </div>
              </div>
            </Card>
          </motion.div>
        </motion.div>
      </div>
    </section>
  )
}
